apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - image: examplevotingapp.azurecr.io/worker-service:20241231-6dd3525
        name: worker
      imagePullSecrets:
      - name: acr-secret
