name: Build and Push Result Service to ACR

on:
  push:
    paths:
      - "result/**"

jobs:
  build-and-push-result-service:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["18.x"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/result-service:latest ./result
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/result-service:latest
