name: Build and Push Vote Service to ACR
on:
  push:
    paths:
      - "vote/**"
jobs:
  build-and-push-vote-service:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/vote-service:latest ./vote
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/vote-service:latest
