name: Build and Push Result Service to ACR

on:
  push:
    paths:
      - "result/**"

permissions:
  contents: write

jobs:
  build-and-push-result-service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ github.token }}
          fetch-depth: 0

      - name: Set Tag as Environment Variable
        run: echo "IMAGE_TAG=$(date +'%Y%m%d')-${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/result-service:${IMAGE_TAG} ./result
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/result-service:${IMAGE_TAG}

      - name: Configure Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Update K8s manifest
        run: |
          sed -i "s|image:.*|image: ${{ secrets.ACR_LOGIN_SERVER }}/result-service:${IMAGE_TAG}|g" k8s-specifications/result-deployment.yaml
          git add k8s-specifications/result-deployment.yaml
          git commit -m "Update result deployment to image tag ${IMAGE_TAG}"
          git push
