name: Build and Push Vote Service to ACR
on:
  push:
    paths:
      - "vote/**"

# Add permissions block
permissions:
  contents: write

jobs:
  build-and-push-vote-service:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Tag as Environment Variable
        run: echo "IMAGE_TAG=$(date +'%Y%m%d')-${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/vote-service:${IMAGE_TAG} ./vote
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/vote-service:${IMAGE_TAG}

      - name: Update K8s manifest
        uses: ./.github/actions/update-k8s-manifest
        with:
          service-name: 'vote'
          image-name: ${{ secrets.ACR_LOGIN_SERVER }}/vote-service
          image-tag: ${IMAGE_TAG}
