name: Build and Push Worker Service to ACR

on:
  push:
    paths:
      - "worker/**"

jobs:
  build-and-push-worker-service:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ["7.0.x"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/worker-service:latest ./worker
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/worker-service:latest
