name: Build and Push Result Service to ACR

on:
  push:
    paths:
      - "result/**"

permissions:
  contents: write

jobs:
  build-and-push-result-service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Tag as Environment Variable
        run: echo "IMAGE_TAG=$(date +'%Y%m%d')-${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/result-service:${IMAGE_TAG} ./result
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/result-service:${IMAGE_TAG}

      - name: Update K8s manifests
        run: |
          chmod +x ./scripts/updateK8sManifests.sh
          ./scripts/updateK8sManifests.sh "result" "${{ secrets.ACR_LOGIN_SERVER }}/result-service" "${IMAGE_TAG}"
